### ISSUE TITLE
Repex failing archer

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.repex.at#66] opened 2015-10-20 16:45 UTC
Verbose log: https://gist.github.com/vivek-bala/7735f8c8045375493f18

It seemed to be fine in the morning. Submitted on to the queue and was pending. I reran it now, it fails with `saga.exceptions.NoSuccess: Could not detect shell prompt`.

**Comment by andre-merzky** [comment] 2015-10-20 17:05
Can you please try again?  This looks like a connection  timeout...  Can you log into archer otherwise?  Please try with:

```
/usr/bin/env TERM=vt100 /usr/bin/ssh -t -o IdentityFile=/home/vivek/.ssh/id_rsa -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_vivek_%h_%p.vb224.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 vb224@login.archer.ac.uk
```

preferably _while_ the application is hanging and prints those `HELLO_%d_SAGA` log messages...

**Comment by vivek-bala** [comment] 2015-10-20 17:26
> Can you please try again? This looks like a connection timeout...

This is repeatable. I get this everytime now. Will try the command you mentioned now.

> Can you log into archer otherwise?

Yes.

**Comment by vivek-bala** [comment] 2015-10-20 17:30
I get the same error again: `saga.exceptions.NoSuccess: Could not detect shell prompt`

On executing the following command,

```
$ /usr/bin/env TERM=vt100 /usr/bin/ssh -t -o IdentityFile=/home/vivek/.ssh/id_rsa -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_vivek_%h_%p.vb224.ctrl -o TCPKeepAlive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 vb224@login.archer.ac.uk
```

I don't get any output/message. It just hangs. This is from the VM. I was able to log into Archer during this time.

**Comment by andre-merzky** [comment] 2015-10-20 17:43
That hang is exactly what also then hangs in SAGA :/  I am not exactly sure what to do about that though - no ssh connectivity is nothing we can fix or work around in the radical stack :/

**Comment by vivek-bala** [comment] 2015-10-20 17:50
I don't understand the difference between what saga does (assuming the above command is what saga executes) and a normal ssh into the machine (which was successful). Rather, pondering over why one works and not the other.

**Comment by marksantcroos** [comment] 2015-10-20 17:55
Can you remove any /tmp/saga_ssh_\* files and try again?

**Comment by vivek-bala** [comment] 2015-10-20 17:58
Ok, that worked ! The job is now in the queue.

**Comment by vivek-bala** [comment] 2015-10-20 18:00
@marksantcroos What exactly was happening ?

**Comment by andre-merzky** [comment] 2015-10-20 18:04
The ssh master channel either died or got stuck.  Removing that file prompted ssh to create a new one...

**Comment by andre-merzky** [comment] 2015-10-20 18:05
I am not exactly sure how to avoid/detect that situation.  It is not the first time this happened, but it is also not very frequent, thus hard to reproduce.  We  probably won't touch that code path right now, but eventually that deserves some recovering mechanism.

**Comment by antonst** [comment] 2016-04-20 22:34
Is this issue still relevant for `devel` branch? If not I am closing this ticket.

**Comment by antonst** [comment] 2016-04-25 16:49
closed due to lack of response

**Closed as completed by antonst** 2016-04-25 16:49 UTC
